apiVersion: v1
kind: Pod
metadata:
  name: hostpath-pod
  namespace: audit-zone
spec:
  containers:
    - name: nginx
      image: nginx
  volumes:
    - name: hostdata
      hostPath:
        path: /etc