# rolebinding.yaml
# admin
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: devops-admin-binding
subjects:
  - kind: ServiceAccount
    name: admin
    namespace: propdevelopment
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
# security
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: security-binding
subjects:
  - kind: ServiceAccount
    name: security
    namespace: propdevelopment
roleRef:
  kind: ClusterRole
  name: cluster-secret
  apiGroup: rbac.authorization.k8s.io
---
# staff
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: watcher-binding
subjects:
  - kind: ServiceAccount
    name: staff
    namespace: propdevelopment
roleRef:
  kind: ClusterRole
  name: cluster-staff
  apiGroup: rbac.authorization.k8s.io
---
# smarthome-operator
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: smarthome-operator-binding
  namespace: smarthome
subjects:
  - kind: ServiceAccount
    name: smarthome-operator
    namespace: smarthome
roleRef:
  kind: Role
  name: smarthome-admin
  apiGroup: rbac.authorization.k8s.io